USE [master]
GO

/****** Object:  Database [pos2]    Script Date: 03/02/2020 17:43:02 ******/
CREATE DATABASE [pos2] ON  PRIMARY 
( NAME = N'pos', FILENAME = N'D:\pos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'pos_log', FILENAME = N'D:\pos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [pos2] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pos2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pos2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pos2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pos2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pos2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pos2] SET ARITHABORT OFF 
GO

ALTER DATABASE [pos2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [pos2] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [pos2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pos2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pos2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pos2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pos2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pos2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pos2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pos2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pos2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [pos2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pos2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pos2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pos2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pos2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pos2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pos2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pos2] SET  READ_WRITE 
GO

ALTER DATABASE [pos2] SET RECOVERY FULL 
GO

ALTER DATABASE [pos2] SET  MULTI_USER 
GO

ALTER DATABASE [pos2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pos2] SET DB_CHAINING OFF 
GO


